// @ts-ignore — generated by `vite build` (adapter-cloudflare); untyped.
import app from '../.svelte-kit/cloudflare/_worker.js';
import { tick } from '../src/lib/server/engine';
import type { BonkEnv } from '../src/lib/server/types';

export default {
	fetch(request: Request, env: BonkEnv, ctx: ExecutionContext) {
		return app.fetch(request, env, ctx);
	},
	async scheduled(_controller: ScheduledController, env: BonkEnv, ctx: ExecutionContext) {
		ctx.waitUntil(
			tick(env).then(
				(r) => console.log(`tick: ${r.checked} checked, ${r.alerts} alerts`),
				(e) => console.error('tick failed', e)
			)
		);
	}
};
